version: "3"

vars:
  package_name: "mkdocs-embed-file-plugin"
  pyproject_dir: "{{.Taskfile.Dir}}"

tasks:
  default:
    desc: "Run the full release process"
    cmds:
      - task: release

  version:
    desc: "Run semantic-release to determine and bump the version"
    cmds:
      - echo "Running semantic-release to bump the version..."
      - uv run semantic-release -c semantic_release.toml version {{.CLI_ARGS}}

  publish:
    desc: "Publish the package to PyPI"
    cmds:
      - echo "Publishing {{.package_name}} to PyPI..."
      - uv publish 
      - uv run semantic-release -c semantic_release.toml publish

  release:
    desc: "Perform a full release: version bump, build, and publish"
    cmds:
      - task: version
      - task: publish
